CREATE SEQUENCE TBUSUARIO_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
    
CREATE TABLE TBUSUARIO(
    CODIGO  BIGINT NOT NULL DEFAULT NEXTVAL('TBUSUARIO_SEQ'),
    NAME CHARACTER VARYING(60),
    EMAIL CHARACTER VARYING(60),
    ROLE  CHARACTER VARYING(20),
    PASSWORD CHARACTER VARYING(250),
   	CODIGO_CLIENTE BIGINT NOT NULL,
   	ATIVO boolean,
    INCLUSAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ULTIMO_EDICAO TIMESTAMP WITHOUT TIME ZONE
    
    
);
ALTER TABLE TBUSUARIO ADD CONSTRAINT PK_TBUSUARIO PRIMARY KEY (CODIGO);


CREATE SEQUENCE TBPESSOA_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE TBPESSOA(
    CODIGO BIGINT NOT NULL DEFAULT NEXTVAL('TBPESSOA_SEQ'),
    NOME CHARACTER VARYING(80) NOT NULL,
    TIPO_PESSOA CHARACTER VARYING(15) NOT NULL,
    CPF_CNPJ CHARACTER VARYING(30),
    RG CHARACTER VARYING(20),
    TELEFONE CHARACTER VARYING(20),
    EMAIL CHARACTER VARYING(50) NOT NULL,
    DATA_NASCIMENTO DATE
);
ALTER TABLE TBPESSOA ADD CONSTRAINT PK_TBPESSOA PRIMARY KEY (CODIGO);

CREATE SEQUENCE TBGRUPO_POSTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
    
CREATE TABLE TBGRUPO_POSTO(
    CODIGO  BIGINT NOT NULL DEFAULT NEXTVAL('TBGRUPO_POSTO_SEQ'),
    DESCRICAO CHARACTER VARYING(60),
   	ATIVO boolean,
    INCLUSAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ULTIMO_EDICAO TIMESTAMP WITHOUT TIME ZONE
    
    
);
ALTER TABLE TBGRUPO_POSTO ADD CONSTRAINT PK_TBGRUPO_POSTO PRIMARY KEY (CODIGO);


CREATE SEQUENCE TBCLIENTE_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
    
CREATE TABLE TBCLIENTE(
    CODIGO  BIGINT NOT NULL DEFAULT NEXTVAL('TBCLIENTE_SEQ'),
    INSCRICAO_ESTADUAL CHARACTER VARYING(30),
    NOME_FANTASIA  CHARACTER VARYING(100),
    CODIGO_PESSOA BIGINT NOT NULL,
    CODIGO_CIDADE BIGINT,
    CODIGO_GRUPO_POSTO BIGINT,
  	CODIGO_CLIENTE BIGINT,
  	CODIGO_USUARIO_ALTERAR BIGINT,
  	CODIGO_USUARIO_CADASTRO BIGINT,
    ATIVO boolean,
    INCLUSAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ULTIMO_EDICAO TIMESTAMP WITHOUT TIME ZONE
    
    
);
ALTER TABLE TBCLIENTE ADD CONSTRAINT PK_TBCLIENTE PRIMARY KEY (CODIGO);
ALTER TABLE TBCLIENTE ADD CONSTRAINT FK_TBCLIENTE_PESSOA FOREIGN KEY (CODIGO_PESSOA) REFERENCES TBPESSOA(CODIGO);
ALTER TABLE TBCLIENTE ADD CONSTRAINT FK_TBCLIENTE_CIDADE FOREIGN KEY (CODIGO_CIDADE) REFERENCES TBCIDADE(ID);
ALTER TABLE TBCLIENTE ADD CONSTRAINT FK_TBCLIENTE_GRUPO FOREIGN KEY (CODIGO_GRUPO_POSTO) REFERENCES TBGRUPO_POSTO(CODIGO);
ALTER TABLE TBCLIENTE ADD CONSTRAINT FK_TBCLIENTE_US_CADASTAR FOREIGN KEY (CODIGO_USUARIO_CADASTRO) REFERENCES TBUSUARIO(CODIGO);
ALTER TABLE TBCLIENTE ADD CONSTRAINT FK_TBCLIENTE_USU_ALTERAR FOREIGN KEY (CODIGO_USUARIO_ALTERAR) REFERENCES TBUSUARIO(CODIGO);


CREATE SEQUENCE TBICMS_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
    
CREATE TABLE TBICMS(
    CODIGO  BIGINT NOT NULL DEFAULT NEXTVAL('TBICMS_SEQ'),
    DESCRICAO CHARACTER VARYING(60),
    CODIGO_ESTADO BIGINT,
    PORCENTAGEM NUMERIC(15,2) NOT NULL,
   	ATIVO boolean,
    INCLUSAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ULTIMO_EDICAO TIMESTAMP WITHOUT TIME ZONE
    
    
);
ALTER TABLE TBICMS ADD CONSTRAINT PK_TBICMS PRIMARY KEY (CODIGO);
ALTER TABLE TBICMS ADD CONSTRAINT FK_TBICMS_ESTADO FOREIGN KEY (CODIGO_ESTADO) REFERENCES TBESTADO(ID);


CREATE SEQUENCE TBIMPOSTO_FEDERAL_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
    
CREATE TABLE TBIMPOSTO_FEDERAL(
    CODIGO  BIGINT NOT NULL DEFAULT NEXTVAL('TBIMPOSTO_FEDERAL_SEQ'),
    DESCRICAO CHARACTER VARYING(60),
    PIS_PASEP NUMERIC(15,2) NOT NULL,
   	CONFINS NUMERIC(15,2) NOT NULL,
   	CIDE NUMERIC(15,2) NOT NULL,
   	ATIVO boolean,
    INCLUSAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ULTIMO_EDICAO TIMESTAMP WITHOUT TIME ZONE
    
    
);
ALTER TABLE TBIMPOSTO_FEDERAL ADD CONSTRAINT PK_TBIMPOSTO_FEDERAL PRIMARY KEY (CODIGO);


CREATE SEQUENCE TBPRODUTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
    
CREATE TABLE TBPRODUTO(
    CODIGO  BIGINT NOT NULL DEFAULT NEXTVAL('TBPRODUTO_SEQ'),
    DESCRICAO CHARACTER VARYING(60),
    TIPO CHARACTER VARYING(10),
   	UNIDADE CHARACTER VARYING(10),
   	CODIGO_ICMS BIGINT NULL,
   	ATIVO boolean,
    INCLUSAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ULTIMO_EDICAO TIMESTAMP WITHOUT TIME ZONE
    
    
);
ALTER TABLE TBPRODUTO ADD CONSTRAINT PK_TBPRODUTO PRIMARY KEY (CODIGO);
ALTER TABLE TBPRODUTO ADD CONSTRAINT FK_TBPRODUTO_ICMS FOREIGN KEY (CODIGO_ICMS) REFERENCES TBICMS(CODIGO);



CREATE SEQUENCE TBPRODUTO_CLIENTE_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
    
CREATE TABLE TBPRODUTO_CLIENTE(
    CODIGO  BIGINT NOT NULL DEFAULT NEXTVAL('TBPRODUTO_CLIENTE_SEQ'),
    DESCRICAO CHARACTER VARYING(60),
    VALOR_REGIONAL_PRODUTO_IMPORTADOR NUMERIC(15,2) NOT NULL,
   	PRECO_REGIONAL_PRODUTO_IMPORTADOR NUMERIC(15,2) NOT NULL,
   	VALOR_VENDA NUMERIC(15,2) NOT NULL,
   	PRECO_APLICATIVO NUMERIC(15,2) NOT NULL,
   	PRECO_REFERENCIA_ICMS  NUMERIC(15,2) NOT NULL,
   	TIPO CHARACTER VARYING(10),
   	UNIDADE CHARACTER VARYING(10),
   	CODIGO_PRODUTO BIGINT NULL,
   	CODIGO_CLIENTE BIGINT ,
   	ATIVO boolean,
    INCLUSAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ULTIMO_EDICAO TIMESTAMP WITHOUT TIME ZONE
    
    
);
ALTER TABLE TBPRODUTO_CLIENTE ADD CONSTRAINT PK_TBPRODUTO_CLIENTE PRIMARY KEY (CODIGO);
ALTER TABLE TBPRODUTO_CLIENTE ADD CONSTRAINT FK_TBPRODUTO_CLIENTE_PRODUTO FOREIGN KEY (CODIGO_PRODUTO) REFERENCES TBPRODUTO(CODIGO);
ALTER TABLE TBPRODUTO_CLIENTE ADD CONSTRAINT FK_TBPRODUTO_CLIENTE_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES TBCLIENTE(CODIGO);

ALTER TABLE TBUSUARIO ADD CONSTRAINT FK_TBUSUARIO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES TBCLIENTE(CODIGO);
